"""Markdown report generator — produces REPORT.md from triaged findings.

Sections:
  1. Executive Summary (counts, severity distribution)
  2. Findings Table (sortable overview)
  3. Finding Details (per-finding evidence, reproduction, mitigation)
  4. CVE Draft Templates (one per confirmed/potential finding)
  5. Responsible Disclosure guidance
"""

from __future__ import annotations

import logging
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter

from cve_agent.schemas.findings import Finding, FindingStatus, Severity
from cve_agent.triage.triage_agent import TriageReport, TriageVerdict

logger = logging.getLogger("cve_agent.reporting.report_md")

_SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]

_DISCLAIMER = (
    "> **Disclaimer**: This report was generated by an automated analysis "
    "tool. All findings require **manual verification** before any action "
    "is taken. The tool may produce false positives and does NOT guarantee "
    "completeness. Confirmed status indicates dynamic evidence was observed, "
    "not necessarily exploitability."
)

_RESPONSIBLE_DISCLOSURE = """\
## 📋 Responsible Disclosure

If any of the findings in this report affect software used by others, **do not
disclose vulnerabilities publicly** before contacting the maintainers.

**Recommended steps:**

1. **Contact the maintainer** — email `security@<project>` or open a
   private security advisory on GitHub.
2. **Provide details** — share this report (redacted if needed) with
   reproduction steps.
3. **Allow reasonable time** — give the maintainer at least **90 days**
   to address the issue before public disclosure.
4. **Follow coordinated disclosure** — work with the maintainer to
   publish a fix and advisory simultaneously.
5. **Request a CVE** — if the maintainer does not request one, you can
   request a CVE ID via [MITRE](https://cveform.mitre.org/) or
   [GitHub Security Advisories](https://docs.github.com/en/code-security).

**Never use findings from this report for malicious purposes.**
"""


# ── Helpers ───────────────────────────────────────────────


def _severity_badge(s: str) -> str:
    """Markdown severity badge."""
    return {
        "critical": "🔴 Critical",
        "high": "🟠 High",
        "medium": "🟡 Medium",
        "low": "🔵 Low",
        "info": "⚪ Info",
    }.get(s, s)


def _status_badge(s: str) -> str:
    """Markdown status badge."""
    return {
        "confirmed": "✅ Confirmed",
        "potential": "⚠️ Potential",
        "false_positive": "❌ False Positive",
        "candidate": "❓ Candidate",
    }.get(s, s)


def _truncate(text: str, max_len: int = 80) -> str:
    if len(text) <= max_len:
        return text
    return text[:max_len - 3] + "..."


# ── Section builders ──────────────────────────────────────


def _build_header(run_id: str, target: str, generated_at: str) -> str:
    return f"""\
# 🔒 ZeroMint — Security Analysis Report

| Field | Value |
|-------|-------|
| **Run ID** | `{run_id}` |
| **Target** | `{target}` |
| **Generated** | {generated_at} |
| **Tool** | ZeroMint (automated, requires manual verification) |

{_DISCLAIMER}

---
"""


def _build_summary(
    findings: list[Finding],
    triage: TriageReport | None,
) -> str:
    total = len(findings)
    if total == 0:
        return "## 📊 Executive Summary\n\nNo findings to report.\n\n---\n"

    # Status counts
    status_counts = Counter(f.status.value for f in findings)
    confirmed = status_counts.get("confirmed", 0)
    potential = status_counts.get("potential", 0)
    false_pos = status_counts.get("false_positive", 0)
    candidate = status_counts.get("candidate", 0)

    # Severity distribution
    sev_counts = Counter(f.severity.value for f in findings)

    lines = [
        "## 📊 Executive Summary",
        "",
        f"**{total}** findings analyzed.",
        "",
        "| Status | Count |",
        "|--------|-------|",
        f"| ✅ Confirmed | **{confirmed}** |",
        f"| ⚠️ Potential | **{potential}** |",
        f"| ❌ False Positive | {false_pos} |",
        f"| ❓ Candidate | {candidate} |",
        "",
        "### Severity Distribution",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]

    for sev in _SEVERITY_ORDER:
        count = sev_counts.get(sev, 0)
        if count > 0:
            lines.append(f"| {_severity_badge(sev)} | {count} |")

    lines.extend(["", "---", ""])
    return "\n".join(lines)


def _build_findings_table(findings: list[Finding]) -> str:
    if not findings:
        return ""

    # Sort: confirmed first, then by severity
    def sort_key(f: Finding) -> tuple[int, int]:
        status_order = {"confirmed": 0, "potential": 1, "candidate": 2, "false_positive": 3}
        sev_order = {s: i for i, s in enumerate(_SEVERITY_ORDER)}
        return (
            status_order.get(f.status.value, 9),
            sev_order.get(f.severity.value, 9),
        )

    sorted_findings = sorted(findings, key=sort_key)

    lines = [
        "## 📋 Findings Overview",
        "",
        "| # | ID | Title | Severity | Status | Confidence |",
        "|---|----|-------|----------|--------|------------|",
    ]

    for i, f in enumerate(sorted_findings, 1):
        lines.append(
            f"| {i} | `{f.id[:10]}` | {_truncate(f.title, 50)} | "
            f"{_severity_badge(f.severity.value)} | "
            f"{_status_badge(f.status.value)} | "
            f"{f.confidence:.0%} |"
        )

    lines.extend(["", "---", ""])
    return "\n".join(lines)


def _build_finding_detail(
    finding: Finding,
    verdict: TriageVerdict | None,
    index: int,
) -> str:
    lines = [
        f"### {index}. {finding.title}",
        "",
        f"- **ID**: `{finding.id}`",
        f"- **Severity**: {_severity_badge(finding.severity.value)}",
        f"- **Status**: {_status_badge(finding.status.value)}",
        f"- **Confidence**: {finding.confidence:.0%}",
    ]

    if finding.hypothesis:
        hyp = finding.hypothesis
        lines.extend([
            "",
            "#### Hypothesis",
            "",
            f"- **Vulnerability Type**: `{hyp.vuln_type}`",
            f"- **Attack Surface**: {hyp.attack_surface}",
        ])
        if hyp.related_sinks:
            lines.append(f"- **Sinks**: `{'`, `'.join(hyp.related_sinks)}`")
        if hyp.related_sources:
            lines.append(f"- **Sources**: `{'`, `'.join(hyp.related_sources)}`")
        if hyp.self_critique:
            lines.append(f"- **Self-Critique**: {hyp.self_critique}")

    # Evidence
    if finding.evidence:
        lines.extend(["", "#### Evidence", ""])
        for j, ev in enumerate(finding.evidence, 1):
            lines.append(f"**{j}.** [{ev.kind.value}] {ev.summary}")
            if ev.location:
                loc = ev.location
                loc_str = f"`{loc.file}`"
                if loc.start_line:
                    loc_str += f" L{loc.start_line}"
                    if loc.end_line and loc.end_line != loc.start_line:
                        loc_str += f"-{loc.end_line}"
                if loc.symbol:
                    loc_str += f" (`{loc.symbol}`)"
                lines.append(f"   - Location: {loc_str}")
            if ev.snippet:
                lines.append(f"   ```\n   {ev.snippet[:300]}\n   ```")
            if ev.artifact_path:
                lines.append(f"   - Log: `{ev.artifact_path}`")
            lines.append("")

    # Triage rationale
    if verdict:
        lines.extend([
            "#### Triage Rationale",
            "",
            f"> {verdict.rationale}",
            "",
        ])
        if verdict.next_steps:
            lines.append("**Next Steps:**")
            for step in verdict.next_steps:
                lines.append(f"- {step}")
            lines.append("")

    # Reproduction steps
    if finding.reproduction_steps:
        lines.extend(["#### Reproduction Steps", ""])
        for k, step in enumerate(finding.reproduction_steps, 1):
            lines.append(f"{k}. {step}")
        lines.append("")

    # Mitigation
    if finding.mitigation:
        lines.extend([
            "#### Suggested Mitigation",
            "",
            finding.mitigation,
            "",
        ])

    lines.extend(["---", ""])
    return "\n".join(lines)


def _build_cve_draft(finding: Finding, index: int) -> str:
    """Generate a CVE draft template for a confirmed or potential finding."""
    hyp = finding.hypothesis

    vuln_type = hyp.vuln_type if hyp else "unknown"
    attack_surface = hyp.attack_surface if hyp else "TBD"

    # Determine affected info from evidence
    affected_file = "TBD"
    if finding.evidence:
        for ev in finding.evidence:
            if ev.location and ev.location.file:
                affected_file = ev.location.file
                break

    lines = [
        f"### CVE Draft #{index}: {finding.title}",
        "",
        "```",
        f"Title:       {finding.title}",
        f"Type:        {vuln_type}",
        f"Severity:    {finding.severity.value.upper()}",
        f"Confidence:  {finding.confidence:.0%}",
        "",
        "Affected Component:",
        f"  File:      {affected_file}",
        f"  Surface:   {attack_surface}",
        f"  Versions:  TBD (manual verification required)",
        "",
        "Description:",
        f"  Automated analysis identified a potential {vuln_type}",
        f"  vulnerability in the {attack_surface} code path.",
    ]

    if hyp and hyp.exploit_idea:
        lines.extend([
            "",
            "Proof of Concept (non-destructive):",
            f"  {hyp.exploit_idea}",
        ])

    lines.extend([
        "",
        "Impact:",
        f"  Severity assessed as {finding.severity.value}.",
        "  Manual verification is required to determine actual",
        "  exploitability and real-world impact.",
        "  DO NOT overstate — this is an automated assessment.",
    ])

    if finding.reproduction_steps:
        lines.extend(["", "Reproduction Steps:"])
        for k, step in enumerate(finding.reproduction_steps, 1):
            lines.append(f"  {k}. {step}")

    lines.extend([
        "",
        "Suggested Fix:",
        f"  {finding.mitigation or 'TBD — manual review needed'}",
        "",
    ])

    if finding.references:
        lines.append("References:")
        for ref in finding.references:
            lines.append(f"  - {ref}")
        lines.append("")

    lines.extend(["```", "", "---", ""])
    return "\n".join(lines)


# ── Main generator ────────────────────────────────────────


def generate_report_md(
    findings: list[Finding],
    triage_report: TriageReport | None = None,
    *,
    run_id: str = "unknown",
    target: str = "unknown",
) -> str:
    """Generate a complete REPORT.md from triaged findings.

    Args:
        findings: Final findings list (with triage statuses).
        triage_report: Optional triage report for rationale.
        run_id: Pipeline run ID.
        target: Target path/URL.

    Returns:
        Complete Markdown report as a string.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Build verdict lookup
    verdict_map: dict[str, TriageVerdict] = {}
    if triage_report:
        verdict_map = {v.finding_id: v for v in triage_report.verdicts}

    sections: list[str] = []

    # 1. Header
    sections.append(_build_header(run_id, target, now))

    # 2. Summary
    sections.append(_build_summary(findings, triage_report))

    # 3. Findings table
    sections.append(_build_findings_table(findings))

    # 4. Finding details (exclude false_positive)
    actionable = [
        f for f in findings
        if f.status != FindingStatus.FALSE_POSITIVE
    ]

    if actionable:
        sections.append("## 🔍 Finding Details\n")
        for i, f in enumerate(actionable, 1):
            verdict = verdict_map.get(f.id)
            sections.append(_build_finding_detail(f, verdict, i))

    # 5. CVE draft templates (confirmed + potential only)
    cve_candidates = [
        f for f in findings
        if f.status in (FindingStatus.CONFIRMED, FindingStatus.POTENTIAL)
    ]

    if cve_candidates:
        sections.append("## 📝 CVE Draft Templates\n")
        sections.append(
            "> These templates are starting points for responsible disclosure. "
            "All fields marked **TBD** require manual verification.\n\n"
        )
        for i, f in enumerate(cve_candidates, 1):
            sections.append(_build_cve_draft(f, i))

    # 6. False positives (collapsed)
    false_pos = [
        f for f in findings
        if f.status == FindingStatus.FALSE_POSITIVE
    ]
    if false_pos:
        sections.append("## ❌ False Positives (Dismissed)\n")
        sections.append(
            "<details><summary>"
            f"Click to expand ({len(false_pos)} findings dismissed)"
            "</summary>\n"
        )
        for i, f in enumerate(false_pos, 1):
            verdict = verdict_map.get(f.id)
            rationale = verdict.rationale if verdict else "No rationale"
            sections.append(
                f"- **{f.title}** (`{f.id[:10]}`): {_truncate(rationale, 100)}"
            )
        sections.append("\n</details>\n\n---\n")

    # 7. Responsible Disclosure
    sections.append(_RESPONSIBLE_DISCLOSURE)

    # 8. Footer
    sections.append(
        f"\n---\n\n*Report generated by ZeroMint — Run `{run_id}` — {now}*\n"
    )

    return "\n".join(sections)


def save_report(
    report_md: str,
    run_dir: Path,
) -> Path:
    """Save REPORT.md to the run directory."""
    out_path = run_dir / "REPORT.md"
    out_path.write_text(report_md, encoding="utf-8")
    logger.info("Saved report: %s (%d bytes)", out_path, len(report_md))
    return out_path
